-- Lists (grocery/regular checklists) + Routines (streak-free daily sequences).

create table if not exists public.lists (
    id bigint generated by default as identity primary key,
    sales_id bigint references public.sales(id) on delete cascade,
    name text not null,
    emoji text,
    color text,
    position int not null default 0,
    created_at timestamp with time zone not null default now()
);

create table if not exists public.list_items (
    id bigint generated by default as identity primary key,
    list_id bigint not null references public.lists(id) on delete cascade,
    sales_id bigint references public.sales(id) on delete cascade,
    text text not null,
    checked boolean not null default false,
    position int not null default 0,
    created_at timestamp with time zone not null default now()
);

create table if not exists public.routines (
    id bigint generated by default as identity primary key,
    sales_id bigint references public.sales(id) on delete cascade,
    name text not null,
    emoji text,
    color text,
    position int not null default 0,
    created_at timestamp with time zone not null default now()
);

create table if not exists public.routine_steps (
    id bigint generated by default as identity primary key,
    routine_id bigint not null references public.routines(id) on delete cascade,
    sales_id bigint references public.sales(id) on delete cascade,
    text text not null,
    position int not null default 0,
    created_at timestamp with time zone not null default now()
);

create table if not exists public.routine_checks (
    id bigint generated by default as identity primary key,
    step_id bigint not null references public.routine_steps(id) on delete cascade,
    sales_id bigint references public.sales(id) on delete cascade,
    checked_on date not null default current_date,
    created_at timestamp with time zone not null default now(),
    unique (step_id, checked_on)
);

create index if not exists list_items_list_id_idx on public.list_items using btree (list_id);
create index if not exists routine_steps_routine_id_idx on public.routine_steps using btree (routine_id);
create index if not exists routine_checks_checked_on_idx on public.routine_checks using btree (checked_on);

alter table public.lists enable row level security;
alter table public.list_items enable row level security;
alter table public.routines enable row level security;
alter table public.routine_steps enable row level security;
alter table public.routine_checks enable row level security;

create policy "lists_all_own" on public.lists for all to authenticated
    using (sales_id is null or sales_id in (select id from public.sales where user_id = auth.uid()))
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));
create policy "list_items_all_own" on public.list_items for all to authenticated
    using (sales_id is null or sales_id in (select id from public.sales where user_id = auth.uid()))
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));
create policy "routines_all_own" on public.routines for all to authenticated
    using (sales_id is null or sales_id in (select id from public.sales where user_id = auth.uid()))
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));
create policy "routine_steps_all_own" on public.routine_steps for all to authenticated
    using (sales_id is null or sales_id in (select id from public.sales where user_id = auth.uid()))
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));
create policy "routine_checks_all_own" on public.routine_checks for all to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()))
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));

grant select, insert, update, delete on public.lists to authenticated;
grant select, insert, update, delete on public.list_items to authenticated;
grant select, insert, update, delete on public.routines to authenticated;
grant select, insert, update, delete on public.routine_steps to authenticated;
grant select, insert, update, delete on public.routine_checks to authenticated;
grant all on public.lists to service_role;
grant all on public.list_items to service_role;
grant all on public.routines to service_role;
grant all on public.routine_steps to service_role;
grant all on public.routine_checks to service_role;
