-- Command Center hub: embeds, quick-launch tiles, and database links.

create table if not exists public.hub_items (
    id bigint generated by default as identity primary key,
    sales_id bigint references public.sales(id) on delete cascade,
    title text not null,
    url text,
    category text not null default 'Tools',
    kind text not null default 'link',        -- 'embed' | 'link' | 'database'
    description text,
    color text,
    position int not null default 0,
    created_at timestamp with time zone not null default now()
);

create index if not exists hub_items_sales_id_idx on public.hub_items using btree (sales_id);

alter table public.hub_items enable row level security;

create policy "hub_items_select_own" on public.hub_items
    for select to authenticated
    using (sales_id is null or sales_id in (select id from public.sales where user_id = auth.uid()));

create policy "hub_items_insert_own" on public.hub_items
    for insert to authenticated
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));

create policy "hub_items_update_own" on public.hub_items
    for update to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()));

create policy "hub_items_delete_own" on public.hub_items
    for delete to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()));

grant select, insert, update, delete on public.hub_items to authenticated;
grant all on public.hub_items to service_role;
