-- Web push reminders: subscription storage + notification bookkeeping.

create table if not exists public.push_subscriptions (
    id bigint generated by default as identity primary key,
    sales_id bigint not null references public.sales(id) on delete cascade,
    endpoint text not null unique,
    subscription jsonb not null,
    user_agent text,
    created_at timestamp with time zone not null default now()
);

create index if not exists push_subscriptions_sales_id_idx
    on public.push_subscriptions using btree (sales_id);

alter table public.push_subscriptions enable row level security;

-- Owners (matched via sales.user_id = auth.uid()) manage their own subscriptions.
create policy "push_subscriptions_select_own" on public.push_subscriptions
    for select to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()));

create policy "push_subscriptions_insert_own" on public.push_subscriptions
    for insert to authenticated
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));

create policy "push_subscriptions_delete_own" on public.push_subscriptions
    for delete to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()));

grant select, insert, delete on public.push_subscriptions to authenticated;
grant all on public.push_subscriptions to service_role;

-- Track when a task reminder was last sent, so we don't re-notify.
alter table public.tasks add column if not exists reminded_at timestamp with time zone;
