-- Life tracking: user-defined trackers + a stream of log entries.

create table if not exists public.trackers (
    id bigint generated by default as identity primary key,
    sales_id bigint references public.sales(id) on delete cascade,
    name text not null,
    category text not null default 'Life',  -- Life | Business | Skills | Money | ... (open, editable)
    kind text not null default 'check',   -- check | count | scale | note
    unit text,
    color text,
    emoji text,
    position int not null default 0,
    active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create table if not exists public.log_entries (
    id bigint generated by default as identity primary key,
    sales_id bigint references public.sales(id) on delete cascade,
    tracker_id bigint not null references public.trackers(id) on delete cascade,
    value numeric,
    note text,
    logged_at timestamp with time zone not null default now(),
    created_at timestamp with time zone not null default now()
);

create index if not exists trackers_sales_id_idx on public.trackers using btree (sales_id);
create index if not exists log_entries_tracker_id_idx on public.log_entries using btree (tracker_id);
create index if not exists log_entries_logged_at_idx on public.log_entries using btree (logged_at);

alter table public.trackers enable row level security;
alter table public.log_entries enable row level security;

create policy "trackers_all_own" on public.trackers
    for all to authenticated
    using (sales_id is null or sales_id in (select id from public.sales where user_id = auth.uid()))
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));

create policy "log_entries_all_own" on public.log_entries
    for all to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()))
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));

grant select, insert, update, delete on public.trackers to authenticated;
grant select, insert, update, delete on public.log_entries to authenticated;
grant all on public.trackers to service_role;
grant all on public.log_entries to service_role;
