-- Personal To-Dos (task checklists) + Focus (deep-work sessions).

create table if not exists public.todos (
    id bigint generated by default as identity primary key,
    sales_id bigint references public.sales(id) on delete cascade,
    text text not null,
    notes text,
    due_date date,
    priority smallint not null default 1,   -- 0 low, 1 normal, 2 high
    done boolean not null default false,
    done_at timestamp with time zone,
    project_id bigint references public.deals(id) on delete set null,
    position int not null default 0,
    created_at timestamp with time zone not null default now()
);

create index if not exists todos_sales_id_idx on public.todos using btree (sales_id);
create index if not exists todos_due_date_idx on public.todos using btree (due_date);

create table if not exists public.focus_sessions (
    id bigint generated by default as identity primary key,
    sales_id bigint references public.sales(id) on delete cascade,
    label text,
    planned_minutes int not null default 25,
    actual_minutes int,
    started_at timestamp with time zone not null default now(),
    completed boolean not null default false,
    created_at timestamp with time zone not null default now()
);

create index if not exists focus_sessions_sales_id_idx on public.focus_sessions using btree (sales_id);
create index if not exists focus_sessions_started_idx on public.focus_sessions using btree (started_at);

alter table public.todos enable row level security;
alter table public.focus_sessions enable row level security;

create policy "todos_all_own" on public.todos for all to authenticated
    using (sales_id is null or sales_id in (select id from public.sales where user_id = auth.uid()))
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));

create policy "focus_sessions_all_own" on public.focus_sessions for all to authenticated
    using (sales_id is null or sales_id in (select id from public.sales where user_id = auth.uid()))
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));

grant select, insert, update, delete on public.todos to authenticated;
grant select, insert, update, delete on public.focus_sessions to authenticated;
grant all on public.todos to service_role;
grant all on public.focus_sessions to service_role;
