-- Ventures: track businesses/projects-at-scale as entities (status, link, next action).

create table if not exists public.ventures (
    id bigint generated by default as identity primary key,
    sales_id bigint references public.sales(id) on delete cascade,
    name text not null,
    emoji text,
    color text,
    status text not null default 'idea',  -- idea | building | launched | paused | archived
    description text,
    url text,
    next_action text,
    position int not null default 0,
    created_at timestamp with time zone not null default now()
);

create index if not exists ventures_sales_id_idx on public.ventures using btree (sales_id);

alter table public.ventures enable row level security;

create policy "ventures_all_own" on public.ventures for all to authenticated
    using (sales_id is null or sales_id in (select id from public.sales where user_id = auth.uid()))
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));

grant select, insert, update, delete on public.ventures to authenticated;
grant all on public.ventures to service_role;
